### ISSUE TITLE
Adding notify admin button

### ISSUE THREAD

**Issue by xcompass** [ubc/examdb#4]
Update the UI to include a button / link / form for instructors to notify administrator with instruction on file corrections / deletions etc

**Comment by lenglund** [comment]
What will be the contact email for the administrator?

**Comment by xcompass** [comment]
We can do examdb.support@UBC.ca for now.

**Comment by lenglund** [comment]
Admin contact added in a56d25217ef3495f2b9c072ac66103725803bb9b.
